/*
eodhistoricaldata

eodhistoricaldata API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EodBulkLastDayItem struct for EodBulkLastDayItem
type EodBulkLastDayItem struct {
	Date                 *string  `json:"date,omitempty"`
	Code                 *string  `json:"code,omitempty"`
	Type                 *string  `json:"type,omitempty"`
	ExchangeShortName    *string  `json:"exchange_short_name,omitempty"`
	Exchange             *string  `json:"exchange,omitempty"`
	Dividend             *string  `json:"dividend,omitempty"`
	Currency             *string  `json:"currency,omitempty"`
	DeclarationDate      *string  `json:"declarationDate,omitempty"`
	RecordDate           *string  `json:"recordDate,omitempty"`
	PaymentDate          *string  `json:"paymentDate,omitempty"`
	Period               *string  `json:"period,omitempty"`
	UnadjustedValue      *string  `json:"unadjustedValue,omitempty"`
	MarketCapitalization *float64 `json:"MarketCapitalization,omitempty"`
	Beta                 *float64 `json:"Beta,omitempty"`
	Open                 *float64 `json:"open,omitempty"`
	High                 *float64 `json:"high,omitempty"`
	Low                  *float64 `json:"low,omitempty"`
	Close                *float64 `json:"close,omitempty"`
	AdjustedClose        *float64 `json:"adjusted_close,omitempty"`
	Volume               *float64 `json:"volume,omitempty"`
	Ema50d               *float64 `json:"ema_50d,omitempty"`
	Ema200d              *float64 `json:"ema_200d,omitempty"`
	Hi250d               *float64 `json:"hi_250d,omitempty"`
	Lo250d               *float64 `json:"lo_250d,omitempty"`
	Avgvol14d            *float64 `json:"avgvol_14d,omitempty"`
	Avgvol50d            *float64 `json:"avgvol_50d,omitempty"`
	Avgvol200d           *float64 `json:"avgvol_200d,omitempty"`
	Split                *string  `json:"split,omitempty"`
}

// NewEodBulkLastDayItem instantiates a new EodBulkLastDayItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEodBulkLastDayItem() *EodBulkLastDayItem {
	this := EodBulkLastDayItem{}
	return &this
}

// NewEodBulkLastDayItemWithDefaults instantiates a new EodBulkLastDayItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEodBulkLastDayItemWithDefaults() *EodBulkLastDayItem {
	this := EodBulkLastDayItem{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetDate() string {
	if o == nil || o.Date == nil {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetDateOk() (*string, bool) {
	if o == nil || o.Date == nil {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasDate() bool {
	if o != nil && o.Date != nil {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *EodBulkLastDayItem) SetDate(v string) {
	o.Date = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *EodBulkLastDayItem) SetCode(v string) {
	o.Code = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EodBulkLastDayItem) SetType(v string) {
	o.Type = &v
}

// GetExchangeShortName returns the ExchangeShortName field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetExchangeShortName() string {
	if o == nil || o.ExchangeShortName == nil {
		var ret string
		return ret
	}
	return *o.ExchangeShortName
}

// GetExchangeShortNameOk returns a tuple with the ExchangeShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetExchangeShortNameOk() (*string, bool) {
	if o == nil || o.ExchangeShortName == nil {
		return nil, false
	}
	return o.ExchangeShortName, true
}

// HasExchangeShortName returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasExchangeShortName() bool {
	if o != nil && o.ExchangeShortName != nil {
		return true
	}

	return false
}

// SetExchangeShortName gets a reference to the given string and assigns it to the ExchangeShortName field.
func (o *EodBulkLastDayItem) SetExchangeShortName(v string) {
	o.ExchangeShortName = &v
}

// GetExchange returns the Exchange field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetExchange() string {
	if o == nil || o.Exchange == nil {
		var ret string
		return ret
	}
	return *o.Exchange
}

// GetExchangeOk returns a tuple with the Exchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetExchangeOk() (*string, bool) {
	if o == nil || o.Exchange == nil {
		return nil, false
	}
	return o.Exchange, true
}

// HasExchange returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasExchange() bool {
	if o != nil && o.Exchange != nil {
		return true
	}

	return false
}

// SetExchange gets a reference to the given string and assigns it to the Exchange field.
func (o *EodBulkLastDayItem) SetExchange(v string) {
	o.Exchange = &v
}

// GetDividend returns the Dividend field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetDividend() string {
	if o == nil || o.Dividend == nil {
		var ret string
		return ret
	}
	return *o.Dividend
}

// GetDividendOk returns a tuple with the Dividend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetDividendOk() (*string, bool) {
	if o == nil || o.Dividend == nil {
		return nil, false
	}
	return o.Dividend, true
}

// HasDividend returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasDividend() bool {
	if o != nil && o.Dividend != nil {
		return true
	}

	return false
}

// SetDividend gets a reference to the given string and assigns it to the Dividend field.
func (o *EodBulkLastDayItem) SetDividend(v string) {
	o.Dividend = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *EodBulkLastDayItem) SetCurrency(v string) {
	o.Currency = &v
}

// GetDeclarationDate returns the DeclarationDate field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetDeclarationDate() string {
	if o == nil || o.DeclarationDate == nil {
		var ret string
		return ret
	}
	return *o.DeclarationDate
}

// GetDeclarationDateOk returns a tuple with the DeclarationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetDeclarationDateOk() (*string, bool) {
	if o == nil || o.DeclarationDate == nil {
		return nil, false
	}
	return o.DeclarationDate, true
}

// HasDeclarationDate returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasDeclarationDate() bool {
	if o != nil && o.DeclarationDate != nil {
		return true
	}

	return false
}

// SetDeclarationDate gets a reference to the given string and assigns it to the DeclarationDate field.
func (o *EodBulkLastDayItem) SetDeclarationDate(v string) {
	o.DeclarationDate = &v
}

// GetRecordDate returns the RecordDate field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetRecordDate() string {
	if o == nil || o.RecordDate == nil {
		var ret string
		return ret
	}
	return *o.RecordDate
}

// GetRecordDateOk returns a tuple with the RecordDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetRecordDateOk() (*string, bool) {
	if o == nil || o.RecordDate == nil {
		return nil, false
	}
	return o.RecordDate, true
}

// HasRecordDate returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasRecordDate() bool {
	if o != nil && o.RecordDate != nil {
		return true
	}

	return false
}

// SetRecordDate gets a reference to the given string and assigns it to the RecordDate field.
func (o *EodBulkLastDayItem) SetRecordDate(v string) {
	o.RecordDate = &v
}

// GetPaymentDate returns the PaymentDate field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetPaymentDate() string {
	if o == nil || o.PaymentDate == nil {
		var ret string
		return ret
	}
	return *o.PaymentDate
}

// GetPaymentDateOk returns a tuple with the PaymentDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetPaymentDateOk() (*string, bool) {
	if o == nil || o.PaymentDate == nil {
		return nil, false
	}
	return o.PaymentDate, true
}

// HasPaymentDate returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasPaymentDate() bool {
	if o != nil && o.PaymentDate != nil {
		return true
	}

	return false
}

// SetPaymentDate gets a reference to the given string and assigns it to the PaymentDate field.
func (o *EodBulkLastDayItem) SetPaymentDate(v string) {
	o.PaymentDate = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetPeriod() string {
	if o == nil || o.Period == nil {
		var ret string
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetPeriodOk() (*string, bool) {
	if o == nil || o.Period == nil {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasPeriod() bool {
	if o != nil && o.Period != nil {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given string and assigns it to the Period field.
func (o *EodBulkLastDayItem) SetPeriod(v string) {
	o.Period = &v
}

// GetUnadjustedValue returns the UnadjustedValue field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetUnadjustedValue() string {
	if o == nil || o.UnadjustedValue == nil {
		var ret string
		return ret
	}
	return *o.UnadjustedValue
}

// GetUnadjustedValueOk returns a tuple with the UnadjustedValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetUnadjustedValueOk() (*string, bool) {
	if o == nil || o.UnadjustedValue == nil {
		return nil, false
	}
	return o.UnadjustedValue, true
}

// HasUnadjustedValue returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasUnadjustedValue() bool {
	if o != nil && o.UnadjustedValue != nil {
		return true
	}

	return false
}

// SetUnadjustedValue gets a reference to the given string and assigns it to the UnadjustedValue field.
func (o *EodBulkLastDayItem) SetUnadjustedValue(v string) {
	o.UnadjustedValue = &v
}

// GetMarketCapitalization returns the MarketCapitalization field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetMarketCapitalization() float64 {
	if o == nil || o.MarketCapitalization == nil {
		var ret float64
		return ret
	}
	return *o.MarketCapitalization
}

// GetMarketCapitalizationOk returns a tuple with the MarketCapitalization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetMarketCapitalizationOk() (*float64, bool) {
	if o == nil || o.MarketCapitalization == nil {
		return nil, false
	}
	return o.MarketCapitalization, true
}

// HasMarketCapitalization returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasMarketCapitalization() bool {
	if o != nil && o.MarketCapitalization != nil {
		return true
	}

	return false
}

// SetMarketCapitalization gets a reference to the given float64 and assigns it to the MarketCapitalization field.
func (o *EodBulkLastDayItem) SetMarketCapitalization(v float64) {
	o.MarketCapitalization = &v
}

// GetBeta returns the Beta field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetBeta() float64 {
	if o == nil || o.Beta == nil {
		var ret float64
		return ret
	}
	return *o.Beta
}

// GetBetaOk returns a tuple with the Beta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetBetaOk() (*float64, bool) {
	if o == nil || o.Beta == nil {
		return nil, false
	}
	return o.Beta, true
}

// HasBeta returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasBeta() bool {
	if o != nil && o.Beta != nil {
		return true
	}

	return false
}

// SetBeta gets a reference to the given float64 and assigns it to the Beta field.
func (o *EodBulkLastDayItem) SetBeta(v float64) {
	o.Beta = &v
}

// GetOpen returns the Open field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetOpen() float64 {
	if o == nil || o.Open == nil {
		var ret float64
		return ret
	}
	return *o.Open
}

// GetOpenOk returns a tuple with the Open field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetOpenOk() (*float64, bool) {
	if o == nil || o.Open == nil {
		return nil, false
	}
	return o.Open, true
}

// HasOpen returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasOpen() bool {
	if o != nil && o.Open != nil {
		return true
	}

	return false
}

// SetOpen gets a reference to the given float64 and assigns it to the Open field.
func (o *EodBulkLastDayItem) SetOpen(v float64) {
	o.Open = &v
}

// GetHigh returns the High field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetHigh() float64 {
	if o == nil || o.High == nil {
		var ret float64
		return ret
	}
	return *o.High
}

// GetHighOk returns a tuple with the High field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetHighOk() (*float64, bool) {
	if o == nil || o.High == nil {
		return nil, false
	}
	return o.High, true
}

// HasHigh returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasHigh() bool {
	if o != nil && o.High != nil {
		return true
	}

	return false
}

// SetHigh gets a reference to the given float64 and assigns it to the High field.
func (o *EodBulkLastDayItem) SetHigh(v float64) {
	o.High = &v
}

// GetLow returns the Low field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetLow() float64 {
	if o == nil || o.Low == nil {
		var ret float64
		return ret
	}
	return *o.Low
}

// GetLowOk returns a tuple with the Low field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetLowOk() (*float64, bool) {
	if o == nil || o.Low == nil {
		return nil, false
	}
	return o.Low, true
}

// HasLow returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasLow() bool {
	if o != nil && o.Low != nil {
		return true
	}

	return false
}

// SetLow gets a reference to the given float64 and assigns it to the Low field.
func (o *EodBulkLastDayItem) SetLow(v float64) {
	o.Low = &v
}

// GetClose returns the Close field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetClose() float64 {
	if o == nil || o.Close == nil {
		var ret float64
		return ret
	}
	return *o.Close
}

// GetCloseOk returns a tuple with the Close field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetCloseOk() (*float64, bool) {
	if o == nil || o.Close == nil {
		return nil, false
	}
	return o.Close, true
}

// HasClose returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasClose() bool {
	if o != nil && o.Close != nil {
		return true
	}

	return false
}

// SetClose gets a reference to the given float64 and assigns it to the Close field.
func (o *EodBulkLastDayItem) SetClose(v float64) {
	o.Close = &v
}

// GetAdjustedClose returns the AdjustedClose field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetAdjustedClose() float64 {
	if o == nil || o.AdjustedClose == nil {
		var ret float64
		return ret
	}
	return *o.AdjustedClose
}

// GetAdjustedCloseOk returns a tuple with the AdjustedClose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetAdjustedCloseOk() (*float64, bool) {
	if o == nil || o.AdjustedClose == nil {
		return nil, false
	}
	return o.AdjustedClose, true
}

// HasAdjustedClose returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasAdjustedClose() bool {
	if o != nil && o.AdjustedClose != nil {
		return true
	}

	return false
}

// SetAdjustedClose gets a reference to the given float64 and assigns it to the AdjustedClose field.
func (o *EodBulkLastDayItem) SetAdjustedClose(v float64) {
	o.AdjustedClose = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetVolume() float64 {
	if o == nil || o.Volume == nil {
		var ret float64
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetVolumeOk() (*float64, bool) {
	if o == nil || o.Volume == nil {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasVolume() bool {
	if o != nil && o.Volume != nil {
		return true
	}

	return false
}

// SetVolume gets a reference to the given float64 and assigns it to the Volume field.
func (o *EodBulkLastDayItem) SetVolume(v float64) {
	o.Volume = &v
}

// GetEma50d returns the Ema50d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetEma50d() float64 {
	if o == nil || o.Ema50d == nil {
		var ret float64
		return ret
	}
	return *o.Ema50d
}

// GetEma50dOk returns a tuple with the Ema50d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetEma50dOk() (*float64, bool) {
	if o == nil || o.Ema50d == nil {
		return nil, false
	}
	return o.Ema50d, true
}

// HasEma50d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasEma50d() bool {
	if o != nil && o.Ema50d != nil {
		return true
	}

	return false
}

// SetEma50d gets a reference to the given float64 and assigns it to the Ema50d field.
func (o *EodBulkLastDayItem) SetEma50d(v float64) {
	o.Ema50d = &v
}

// GetEma200d returns the Ema200d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetEma200d() float64 {
	if o == nil || o.Ema200d == nil {
		var ret float64
		return ret
	}
	return *o.Ema200d
}

// GetEma200dOk returns a tuple with the Ema200d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetEma200dOk() (*float64, bool) {
	if o == nil || o.Ema200d == nil {
		return nil, false
	}
	return o.Ema200d, true
}

// HasEma200d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasEma200d() bool {
	if o != nil && o.Ema200d != nil {
		return true
	}

	return false
}

// SetEma200d gets a reference to the given float64 and assigns it to the Ema200d field.
func (o *EodBulkLastDayItem) SetEma200d(v float64) {
	o.Ema200d = &v
}

// GetHi250d returns the Hi250d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetHi250d() float64 {
	if o == nil || o.Hi250d == nil {
		var ret float64
		return ret
	}
	return *o.Hi250d
}

// GetHi250dOk returns a tuple with the Hi250d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetHi250dOk() (*float64, bool) {
	if o == nil || o.Hi250d == nil {
		return nil, false
	}
	return o.Hi250d, true
}

// HasHi250d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasHi250d() bool {
	if o != nil && o.Hi250d != nil {
		return true
	}

	return false
}

// SetHi250d gets a reference to the given float64 and assigns it to the Hi250d field.
func (o *EodBulkLastDayItem) SetHi250d(v float64) {
	o.Hi250d = &v
}

// GetLo250d returns the Lo250d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetLo250d() float64 {
	if o == nil || o.Lo250d == nil {
		var ret float64
		return ret
	}
	return *o.Lo250d
}

// GetLo250dOk returns a tuple with the Lo250d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetLo250dOk() (*float64, bool) {
	if o == nil || o.Lo250d == nil {
		return nil, false
	}
	return o.Lo250d, true
}

// HasLo250d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasLo250d() bool {
	if o != nil && o.Lo250d != nil {
		return true
	}

	return false
}

// SetLo250d gets a reference to the given float64 and assigns it to the Lo250d field.
func (o *EodBulkLastDayItem) SetLo250d(v float64) {
	o.Lo250d = &v
}

// GetAvgvol14d returns the Avgvol14d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetAvgvol14d() float64 {
	if o == nil || o.Avgvol14d == nil {
		var ret float64
		return ret
	}
	return *o.Avgvol14d
}

// GetAvgvol14dOk returns a tuple with the Avgvol14d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetAvgvol14dOk() (*float64, bool) {
	if o == nil || o.Avgvol14d == nil {
		return nil, false
	}
	return o.Avgvol14d, true
}

// HasAvgvol14d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasAvgvol14d() bool {
	if o != nil && o.Avgvol14d != nil {
		return true
	}

	return false
}

// SetAvgvol14d gets a reference to the given float64 and assigns it to the Avgvol14d field.
func (o *EodBulkLastDayItem) SetAvgvol14d(v float64) {
	o.Avgvol14d = &v
}

// GetAvgvol50d returns the Avgvol50d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetAvgvol50d() float64 {
	if o == nil || o.Avgvol50d == nil {
		var ret float64
		return ret
	}
	return *o.Avgvol50d
}

// GetAvgvol50dOk returns a tuple with the Avgvol50d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetAvgvol50dOk() (*float64, bool) {
	if o == nil || o.Avgvol50d == nil {
		return nil, false
	}
	return o.Avgvol50d, true
}

// HasAvgvol50d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasAvgvol50d() bool {
	if o != nil && o.Avgvol50d != nil {
		return true
	}

	return false
}

// SetAvgvol50d gets a reference to the given float64 and assigns it to the Avgvol50d field.
func (o *EodBulkLastDayItem) SetAvgvol50d(v float64) {
	o.Avgvol50d = &v
}

// GetAvgvol200d returns the Avgvol200d field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetAvgvol200d() float64 {
	if o == nil || o.Avgvol200d == nil {
		var ret float64
		return ret
	}
	return *o.Avgvol200d
}

// GetAvgvol200dOk returns a tuple with the Avgvol200d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetAvgvol200dOk() (*float64, bool) {
	if o == nil || o.Avgvol200d == nil {
		return nil, false
	}
	return o.Avgvol200d, true
}

// HasAvgvol200d returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasAvgvol200d() bool {
	if o != nil && o.Avgvol200d != nil {
		return true
	}

	return false
}

// SetAvgvol200d gets a reference to the given float64 and assigns it to the Avgvol200d field.
func (o *EodBulkLastDayItem) SetAvgvol200d(v float64) {
	o.Avgvol200d = &v
}

// GetSplit returns the Split field value if set, zero value otherwise.
func (o *EodBulkLastDayItem) GetSplit() string {
	if o == nil || o.Split == nil {
		var ret string
		return ret
	}
	return *o.Split
}

// GetSplitOk returns a tuple with the Split field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EodBulkLastDayItem) GetSplitOk() (*string, bool) {
	if o == nil || o.Split == nil {
		return nil, false
	}
	return o.Split, true
}

// HasSplit returns a boolean if a field has been set.
func (o *EodBulkLastDayItem) HasSplit() bool {
	if o != nil && o.Split != nil {
		return true
	}

	return false
}

// SetSplit gets a reference to the given string and assigns it to the Split field.
func (o *EodBulkLastDayItem) SetSplit(v string) {
	o.Split = &v
}

func (o EodBulkLastDayItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Date != nil {
		toSerialize["date"] = o.Date
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.ExchangeShortName != nil {
		toSerialize["exchange_short_name"] = o.ExchangeShortName
	}
	if o.Exchange != nil {
		toSerialize["exchange"] = o.Exchange
	}
	if o.Dividend != nil {
		toSerialize["dividend"] = o.Dividend
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.DeclarationDate != nil {
		toSerialize["declarationDate"] = o.DeclarationDate
	}
	if o.RecordDate != nil {
		toSerialize["recordDate"] = o.RecordDate
	}
	if o.PaymentDate != nil {
		toSerialize["paymentDate"] = o.PaymentDate
	}
	if o.Period != nil {
		toSerialize["period"] = o.Period
	}
	if o.UnadjustedValue != nil {
		toSerialize["unadjustedValue"] = o.UnadjustedValue
	}
	if o.MarketCapitalization != nil {
		toSerialize["MarketCapitalization"] = o.MarketCapitalization
	}
	if o.Beta != nil {
		toSerialize["Beta"] = o.Beta
	}
	if o.Open != nil {
		toSerialize["open"] = o.Open
	}
	if o.High != nil {
		toSerialize["high"] = o.High
	}
	if o.Low != nil {
		toSerialize["low"] = o.Low
	}
	if o.Close != nil {
		toSerialize["close"] = o.Close
	}
	if o.AdjustedClose != nil {
		toSerialize["adjusted_close"] = o.AdjustedClose
	}
	if o.Volume != nil {
		toSerialize["volume"] = o.Volume
	}
	if o.Ema50d != nil {
		toSerialize["ema_50d"] = o.Ema50d
	}
	if o.Ema200d != nil {
		toSerialize["ema_200d"] = o.Ema200d
	}
	if o.Hi250d != nil {
		toSerialize["hi_250d"] = o.Hi250d
	}
	if o.Lo250d != nil {
		toSerialize["lo_250d"] = o.Lo250d
	}
	if o.Avgvol14d != nil {
		toSerialize["avgvol_14d"] = o.Avgvol14d
	}
	if o.Avgvol50d != nil {
		toSerialize["avgvol_50d"] = o.Avgvol50d
	}
	if o.Avgvol200d != nil {
		toSerialize["avgvol_200d"] = o.Avgvol200d
	}
	if o.Split != nil {
		toSerialize["split"] = o.Split
	}
	return json.Marshal(toSerialize)
}

type NullableEodBulkLastDayItem struct {
	value *EodBulkLastDayItem
	isSet bool
}

func (v NullableEodBulkLastDayItem) Get() *EodBulkLastDayItem {
	return v.value
}

func (v *NullableEodBulkLastDayItem) Set(val *EodBulkLastDayItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEodBulkLastDayItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEodBulkLastDayItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEodBulkLastDayItem(val *EodBulkLastDayItem) *NullableEodBulkLastDayItem {
	return &NullableEodBulkLastDayItem{value: val, isSet: true}
}

func (v NullableEodBulkLastDayItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEodBulkLastDayItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
